server.port=8082
spring.application.name=skills-tute

spring.profiles.active=dev

spring.cache.type=simple
st.spring.caches=topics,companies,interview-questions,countries,cities

st.add.question.points=30
st.update.question.points=15
st.reduce.question.points=1
st.like.points=10
st.unlike.points=5