server.port=8082
spring.application.name=skills-tute

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://localhost:5432/skills-tute
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

jwt.secret=VGhpc0lzQVN0cm9uZ1NlY3JldEtleUZvckp3dFRva2VuMTIzNDU2Nzg5MDEyMzQ=