server.port=8081

spring.application.name=Skills-Tutorial

spring.datasource.url=jdbc:postgresql://localhost:5432/skills-tute
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true

jwt.secret=VGhpc0lzQVN0cm9uZ1NlY3JldEtleUZvckp3dFRva2VuMTIzNDU2Nzg5MDEyMzQ=