server.port=8082
spring.application.name=skills-tute

spring.profiles.active=dev

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.db.enabled=true

spring.cache.type=simple
st.spring.caches=topics,companies,interview-questions,countries,cities
st.spring.refresh.caches=topics,companies,interview-questions,countries,cities

st.add.question.points=50
st.update.question.points=25
st.reduce.question.points=1
st.like.points=25
st.dislike.points=15
st.star.points=2

st.add.answer.points=30
st.reduce.answer.points=1

st.reward.value.inr=0.20
st.add.question.rewards=50
st.add.answer.rewards=50
st.update.question.rewards=25
st.like.rewards=10
st.unlike.rewards=5
st.star.rewards=5

spring.messages.basename=messages
spring.messages.encoding: UTF-8
spring.messages.fallback-to-system-locale=false

#select * from topic_types;
#select * from topics_topic_types;
#insert into topic_types values(1, 'TUTORIAL');
#insert into topic_types values(2, 'INTERVIEW');
#insert into topic_types values(3, 'PROGRAMMING');
#insert into topic_types values(4, 'QUIZ');
#insert into topic_types values(5, 'NOTES');